In [4]:
import pandas as pd
import numpy as np
from sklearn import linear_model

#configuro notebook para mostrar varios salidas en la misma celda
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
#amplio el output de columnas a 500
pd.set_option('display.max_columns', 500)



In [8]:
dic_all_files={'Accvict':'./cleaned/view_accvict_08_15.csv','Pers':'./cleaned/view_pers_08_15.csv','Vehic':'./cleaned/view_vehic_08_15.csv'}

dic_all_files["Accvict"]

'./cleaned/view_accvict_08_15.csv'

In [37]:
from matplotlib import pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans



array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
print ("-----------------------------------------------------\n")
print ("VISTA CON LOS DATOS DE ACCIDENTES DESDE 2008 A 2015\n")
print ("-----------------------------------------------------\n")

df_acc=pd.read_csv(dic_all_files["Accvict"],delimiter=";",encoding="ISO-8859-1",dtype={'ID_ACCIDENTE': object})
df_acc.head(5)
df_acc.info()

print ("-----------------------------------------------------\n")
print ("VISTA CON LOS DATOS DE PERSONAS DESDE 2008 A 2015\n")
print ("-----------------------------------------------------\n")

df_acc=pd.read_csv(dic_all_files["Pers"],delimiter=";",encoding="ISO-8859-1",dtype={'ID_ACCIDENTE': object})
df_acc.head(5)
df_acc.info()

print ("-----------------------------------------------------\n")
print ("VISTA CON LOS DATOS DE VEHICULOS DESDE 2008 A 2015\n")
print ("-----------------------------------------------------\n")

df_acc=pd.read_csv(dic_all_files["Vehic"],delimiter=";",encoding="ISO-8859-1",dtype={'ID_ACCIDENTE': object})
df_acc.head(5)
df_acc.info()

-----------------------------------------------------

VISTA CON LOS DATOS DE ACCIDENTES DESDE 2008 A 2015

-----------------------------------------------------



ID_ACCIDENTE  ANIO  MES  HORA  DIASEMANA  PROVINCIA  COMUNIDAD_AUTONOMA  \
0  2008480000372  2008    4     7          5         48                  17   
1  2008250021218  2008    3    14          7         25                   9   
2  2008430024095  2008   10    12          7         43                   9   
3  2008430022973  2008    4    18          2         43                   9   
4  2008250021457  2008    5    19          5         25                   9   

   TOT_VICTIMAS  TOT_MUERTOS  TOT_HERIDOS_GRAVES  TOT_HERIDOS_LEVES  \
0             4            0                   0                  4   
1             1            0                   1                  0   
2             1            0                   0                  1   
3             1            0                   0                  1   
4             1            0                   1                  0   

   TOT_VEHICULOS_IMPLICADOS  ZONA  ZONA_AGRUPADA  RED_CARRETERA  TIPO_VIA  \
0                         1     1              1              3         2   
1                         1     1              1              2         5   
2                         1     1              1              4         5   
3                         2     1              1              4         5   
4                         1     1              1              4         9   

   SUPERFICIE_CALZADA  LUMINOSIDAD  FACTORES_ATMOSFERICOS  \
0                   2            3                      1   
1                   1            1                      9   
2                   1            1                      1   
3                   1            1                      1   
4                   9            1                      9   

   VISIBILIDAD_RESTRINGIDA  TIPO_ACCIDENTE  
0                        8              71  
1                        8              22  
2                        0              68  
3                        0              14  
4                        8              66

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 711902 entries, 0 to 711901
Data columns (total 21 columns):
ID_ACCIDENTE                711902 non-null object
ANIO                        711902 non-null int64
MES                         711902 non-null int64
HORA                        711902 non-null int64
DIASEMANA                   711902 non-null int64
PROVINCIA                   711902 non-null int64
COMUNIDAD_AUTONOMA          711902 non-null int64
TOT_VICTIMAS                711902 non-null int64
TOT_MUERTOS                 711902 non-null int64
TOT_HERIDOS_GRAVES          711902 non-null int64
TOT_HERIDOS_LEVES           711902 non-null int64
TOT_VEHICULOS_IMPLICADOS    711902 non-null int64
ZONA                        711902 non-null int64
ZONA_AGRUPADA               711902 non-null int64
RED_CARRETERA               711902 non-null int64
TIPO_VIA                    711902 non-null int64
SUPERFICIE_CALZADA          711902 non-null int64
LUMINOSIDAD                 711902 non

ID_ACCIDENTE  ID_VEHICULO  ID_PERSONA  ID_CONDUCTOR  ID_PASAJERO  \
0  2008010000001            1           2             1            1   
1  2008010000001            2           2             1            1   
2  2008010000001            2           2             1            2   
3  2008010000001            1           2             1            2   
4  2008010000001            2           1             2            1   

   ID_PEATON  EDAD  ANIO_PERMISO  MANIOBRAS  INFRACC_VELOCIDAD  \
0          1    32          9999         21                  4   
1          1    60          9999         21                  4   
2          1    23          9999         21                  4   
3          1    28          9999         21                  4   
4          1    61          1999          1                  5   

   INFRACC_PEATON  ANIO  
0               9  2008  
1               9  2008  
2               9  2008  
3               9  2008  
4               9  2008

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1724736 entries, 0 to 1724735
Data columns (total 12 columns):
ID_ACCIDENTE         object
ID_VEHICULO          int64
ID_PERSONA           int64
ID_CONDUCTOR         int64
ID_PASAJERO          int64
ID_PEATON            int64
EDAD                 int64
ANIO_PERMISO         int64
MANIOBRAS            int64
INFRACC_VELOCIDAD    int64
INFRACC_PEATON       int64
ANIO                 int64
dtypes: int64(11), object(1)
memory usage: 157.9+ MB
-----------------------------------------------------

VISTA CON LOS DATOS DE VEHICULOS DESDE 2008 A 2015

-----------------------------------------------------



ID_ACCIDENTE  ID_VEHICULO  ANIO_MATRICULA_VEHICULO  \
0  2008410002330            2                     9999   
1  2008520000162            2                     1991   
2  2009460000665            3                     2004   
3  2008460007725            1                     2003   
4  2008410000371            1                     2006   

   MES_MATRICULA_VEHICULO  TIPO_VEHICULO  NUMERO_OCUPANTES_VEH  ANIO  
0                      99             22                     1  2008  
1                      99             22                     1  2008  
2                       1             22                     1  2008  
3                       1             22                     5  2008  
4                       7             22                     1  2008

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1239593 entries, 0 to 1239592
Data columns (total 7 columns):
ID_ACCIDENTE               1239593 non-null object
ID_VEHICULO                1239593 non-null int64
ANIO_MATRICULA_VEHICULO    1239593 non-null int64
MES_MATRICULA_VEHICULO     1239593 non-null int64
TIPO_VEHICULO              1239593 non-null int64
NUMERO_OCUPANTES_VEH       1239593 non-null int64
ANIO                       1239593 non-null int64
dtypes: int64(6), object(1)
memory usage: 66.2+ MB


In [91]:
dic_all_files={'Accvict':"./cleaned/view_accvict_08_15.csv",'Pers':"./cleaned/view_pers_08_15.csv",'Vehic':"./cleaned/view_pers_08_15.csv"}

df_acc=pd.read_csv(dic_all_files["Pers"],delimiter=";",encoding="ISO-8859-1",dtype={'ID_ACCIDENTE': object})
df_acc.head(5)
df_acc.info()

df_acc_2015=df_acc[df_acc['ANIO']==2015]
df_acc_2015=df_acc_2015[['TOT_VICTIMAS','TOT_MUERTOS']]
df_acc_2015.head(5)

df_acc_2015.as_matrix()
KM=KMeans(init='random',n_clusters=3).fit(df_acc_2015)
#Extraemos las medias

L=KM.cluster_centers_

#Extraemos los valores usados para los calculos

Lab=KM.labels_

print(Lab)


fig1= plt.figure(1)
fig.suptitle("Ejemplo de k-medias",fontsize=15)
plot3= plt.scatter(df_acc_2015.values[:,0], df_acc_2015.values[:,1], c=Lab, alpha=0.75)

plt.show()

ID_ACCIDENTE  ID_VEHICULO  ID_PERSONA  ID_CONDUCTOR  ID_PASAJERO  ID_PEATON  \
0  2,00801E+12            1           2             1            1          1   
1  2,00801E+12            2           2             1            1          1   
2  2,00801E+12            2           2             1            2          1   
3  2,00801E+12            1           2             1            2          1   
4  2,00801E+12            2           1             2            1          1   

   EDAD SEXO  ANIO_PERMISO  MANIOBRAS  INFRACC_VELOCIDAD  INFRACC_PEATON  ANIO  
0    32    M          9999         18                  3               9  2008  
1    60    M          9999         18                  3               9  2008  
2    23    V          9999         18                  3               9  2008  
3    28    M          9999         18                  3               9  2008  
4    61    V          9999          1                  5               9  2008

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1633782 entries, 0 to 1633781
Data columns (total 13 columns):
ID_ACCIDENTE         1633782 non-null object
ID_VEHICULO          1633782 non-null int64
ID_PERSONA           1633782 non-null int64
ID_CONDUCTOR         1633782 non-null int64
ID_PASAJERO          1633782 non-null int64
ID_PEATON            1633782 non-null int64
EDAD                 1633782 non-null int64
SEXO                 1633782 non-null object
ANIO_PERMISO         1633782 non-null int64
MANIOBRAS            1633782 non-null int64
INFRACC_VELOCIDAD    1633782 non-null int64
INFRACC_PEATON       1633782 non-null int64
ANIO                 1633782 non-null int64
dtypes: int64(11), object(2)
memory usage: 162.0+ MB


KeyError: "['TOT_VICTIMAS' 'TOT_MUERTOS'] not in index"

In [87]:
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris
iris = load_iris()
pca = PCA(n_components=2).fit(iris.data)
pca_2d = pca.transform(iris.data)
pca_2d

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

array([[-2.68420713,  0.32660731],
       [-2.71539062, -0.16955685],
       [-2.88981954, -0.13734561],
       [-2.7464372 , -0.31112432],
       [-2.72859298,  0.33392456],
       [-2.27989736,  0.74778271],
       [-2.82089068, -0.08210451],
       [-2.62648199,  0.17040535],
       [-2.88795857, -0.57079803],
       [-2.67384469, -0.1066917 ],
       [-2.50652679,  0.65193501],
       [-2.61314272,  0.02152063],
       [-2.78743398, -0.22774019],
       [-3.22520045, -0.50327991],
       [-2.64354322,  1.1861949 ],
       [-2.38386932,  1.34475434],
       [-2.6225262 ,  0.81808967],
       [-2.64832273,  0.31913667],
       [-2.19907796,  0.87924409],
       [-2.58734619,  0.52047364],
       [-2.3105317 ,  0.39786782],
       [-2.54323491,  0.44003175],
       [-3.21585769,  0.14161557],
       [-2.30312854,  0.10552268],
       [-2.35617109, -0.03120959],
       [-2.50791723, -0.13905634],
       [-2.469056  ,  0.13788731],
       [-2.56239095,  0.37468456],
       [-2.63982127,